-- First, remove the table if it exists
BEGIN;
DROP TABLE IF EXISTS highscore_data;

-- Create the table anew
CREATE TABLE highscore_data (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    hours INTEGER NOT NULL,
    minutes INTEGER NOT NULL,
    seconds INTEGER NOT NULL
);

-- insert some test data
-- Using a multi-row insert statement here
--INSERT INTO highscore_data (username,hours,minutes,seconds)
--VALUES
--('Jakel',0,3,5),
--('Kalen',0,3,15);

COMMIT;
        